'use client';
import { FormEvent, useState } from 'react';
import { CitationCard, type CitationView } from './citation-card';

type Turn = { question: string; answer: string; citations: CitationView[] };
export function ChatInterface({ workspaceId, enabled }: { workspaceId: string; enabled: boolean }) {
  const [turns, setTurns] = useState<Turn[]>([]); const [conversationId, setConversationId] = useState<string>(); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const question = new FormData(form).get('question')?.toString().trim(); if (!question) return; setBusy(true); setError(''); const response = await fetch(`/api/workspaces/${workspaceId}/rag`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ question, conversationId }) }).catch(() => null); const body = await response?.json().catch(() => null); if (!response?.ok) setError(body?.error ?? 'Unable to answer'); else { setConversationId(body.conversationId); setTurns((current) => [...current, { question, answer: body.answer, citations: body.citations }]); form.reset(); } setBusy(false); }
  return <section><div className="rag-thread">{turns.map((turn, index) => <div key={`${index}-${turn.question}`}><div className="card"><strong>You</strong><p>{turn.question}</p></div><div className="card"><strong>Document intelligence</strong><p className="rag-answer">{turn.answer}</p></div><div className="citation-grid">{turn.citations.map((citation, citationIndex) => <CitationCard key={`${citation.documentId}-${citationIndex}`} citation={citation} index={citationIndex} />)}</div></div>)}</div><form className="card" onSubmit={submit}><label>Question<textarea name="question" required maxLength={2000} rows={4} placeholder="What changed in revenue, margins, and guidance?" /></label><button className="primary" disabled={!enabled || busy}>{busy ? 'Reviewing sources…' : 'Ask documents'}</button>{!enabled && <p className="note">Chat becomes available after the first document is indexed.</p>}{error && <p className="error-text" role="alert">{error}</p>}</form></section>;
}
