import { NextResponse } from 'next/server';
import { authenticateRequest } from '@/lib/api-auth';
import { weightResultSchema } from '@/lib/portfolio-weights';
import { examplePortfolio } from '@/lib/example-portfolio';
import exampleAllocation from '@/lib/example-portfolio-allocation.json';
import { z } from 'zod';

export const runtime = 'nodejs';
export const maxDuration = 120;
const schema = weightResultSchema.extend({
  data_kind: z.literal('synthetic_educational_example'),
  sample_starting_weights: z.record(z.number().finite()),
  asset_annualized_volatility: z.record(z.number().finite()),
});

export async function GET(req: Request) {
  const session = await authenticateRequest(req);
  if (!session.ok) return session.response;
  try {
    // Generated by services/filings_python/example_portfolio.py from its fixed,
    // seeded synthetic series and the same production eight-method engine.
    const result = schema.parse(exampleAllocation);
    const assets = examplePortfolio.assets.map(asset => asset.ticker);
    if (Object.keys(result.recommendation.recommended_weights).sort().join('|') !== [...assets].sort().join('|') ||
      Object.keys(result.sample_starting_weights).sort().join('|') !== [...assets].sort().join('|')) {
      throw new Error('Example asset contract mismatch');
    }
    return NextResponse.json({ result }, { headers: { 'cache-control': 'private, no-store' } });
  } catch (error) {
    console.error('Example portfolio computation failed', error);
    return NextResponse.json({ error: 'The example allocation is temporarily unavailable. Research and analysis remain available.' }, { status: 502 });
  }
}
